### ISSUE TITLE
How to initialize Carla interface

### ISSUE THREAD

**Issue by CarSanoja** [RobeSafe-UAH/Waypoint_Tracking_Controller#1]
Hello,

First, thank you for your contribution, your results are great! As this is the controller node, could you please explain to me how did you make the interface with Carla? Is there any requirements to replicate your results?

Hope to hear from you soon,

**Comment by rodrigogutierrezm** [comment]
Hello, sorry for the late response. We communicate with the CARLA Simulator using the carla-ros-bridge. We modified the topic names in the ego vehicle script.

**Comment by imamim** [comment]
Thank you for your work. Nice job !!

I've been working with the carla-ros-bridge on car control in carla for a while. I studied your code here, worked on it a little bit, but I could not manage to integrate it with carla-ros-bridge. More precisely, I could not understand what to do. Here I want to ask you a few questions:

1- Is the code you uploaded to this repo compatible with carla-ros-bridge?
2- If possible, can you share your rqtgraph when you integrate it with carla-ros-bridge? I think it will be beneficial for us to solve the problem.

Thanks in advance for your answer !!

**Comment by yigity19** [comment]
> Hello, sorry for the late response. We communicate with the CARLA Simulator using the carla-ros-bridge. We modified the topic names in the ego vehicle script.
Did you changed the names which ego vehicle subscribes to? Thank you

**Comment by rodrigogutierrezm** [comment]
1- The code is not directly compatible. U need to do some changes in the carla ros bridge. The controller publishes the speed and steer cmd in the topics (cmd_vel, steer_cmd and speed_cmd). Also you need to provide an input in form of waypoints, in a ROS message (nav_msgs/Path.msg).

2- Here i share the rqt graph of the entire project. There is a node named control to throttle that transforms the ros topics into carla msgs, similar to the carla ackerman node.
![Captura de pantalla de 2021-04-09 13-23-24](https://user-images.githubusercontent.com/60657571/114173958-39b03680-9938-11eb-9c72-db22a7cb8b0e.png)

**Comment by imamim** [comment]
First of all, thank you for your feedback. We have worked with your code until today after writing it to you and we encountered a few bugs. I want to tell you about them.

First, the Steer value was returning as NaN and we worked on it and saw that the _**R**_ parameter was defined in the code but no value was assigned. This would cause undefined when given to a function as **_(1 / R)_**.

We solved this problem, but now the Steer value is 0 under all conditions. When we debugged the code for a while, we realized that there was a problem with the operations performed within the **_Dlqr function_**. The 2 variables we identified the problem are: **_P0 and Q_**.
Especially the variable **_Q_** has been defined as a matrix above, but it is given to the code without any value. And then the variable that causes the **_Steer value to be 0 is P0_**.

Thanks for your efforts, but we think **the code needs an update**. Probably the code currently loaded is an old version.

We look forward to your return as soon as possible. THANK YOU in advance for your reply.

**Comment by rodrigogutierrezm** [comment]
Hello, 

Your are right, those values are not set. I will update the code as soon as possible, meanwhile you can try to add this in main() (line 440). All these values must be defined in the launch file in order to get a value. 

A[0]=1.0;  A[1]=v * sample_time; A[2]=0.0;  A[3]=1.0;
B[0]=v * (sample_time * sample_time)/2;  B[1]=sample_time;
Q[0]=q11; Q[1]=0.0; Q[2]=0.0; Q[3]=q22;
R=r11;

Thank you.

**Comment by AlJazari1440** [comment]
Dear  @rodrigogutierrezm  

Peace be upon you, kindly will you update this package?

Thanks forward and looking forward to hearing from you soon
Best regards 
Mahmoud Shoshah

**Comment by rodrigogutierrezm** [comment]
Hello, sorry for the late response, I have been really busy.

I have fixed the errors you mentioned in this issue. I have run the node with my project and it works, let me know if you can make it work too. 

However, in order to run it with CARLA simulator, you may need to implement a PI controller to generate an acceleration command (comparing the actual speed of the vehicle and the speed command generated by the waypoint tracking controller) and publish both, the acceleration and steer commands in the "/carla/ego_vehicle/vehicle_control_cmd" topic. Using a CarlaEgoVehicleControl msg.

Good luck.

**Comment by AlJazari1440** [comment]
@rodrigogutierrezm 
Thank you very much for your reply, we have a real robot, so what other tasks we need to do in order to make it run with the real robot?
Because may be that is using the simulator and we need to modify some nodes to make it work with the real robot.

Looking forward to hearing from you
Thanks again
Best regards
Mahmoud Shoshah

**Comment by rodrigogutierrezm** [comment]
Hello, you just need to publish a set of waypoints to be followed in the topic "/waypoints_input" in a msg nav_msgs::Path, and continuosly publish the location of the robot in the topic "/absolute_pose" in a msg nav_msgs::Odometry. All this information is detailed in the article. https://www.mdpi.com/1424-8220/20/14/4062
